# Generated by Django 5.1.6 on 2025-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='cost',
        ),
        migrations.AddField(
            model_name='table',
            name='seat_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
